apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webapp
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  serviceName: "webapp-service"
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-container
        image: nginx:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: webapp-config
