apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0e66108c5c5687739,subnet-03bc771e8eac211db
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
